
var CANVAS_HEIGHT = 360;
var CANVAS_WIDTH = 600;

var ENGINE_TIME_TO_PIXEL_CELERITY = 1 / 100;

var COLLISION_STATUS_NONE = 0;
var COLLISION_STATUS_OVER = 1;
var COLLISION_STATUS_ONCLICK = 3;

var COLLISION_MASK_CURSOR = 1;
var COLLISION_MASK_PASSERBY = 2;
var COLLISION_MASK_WEAPON_CURSOR = 4;
var COLLISION_MASK_WEAPON_PASSERBY = 8;
var COLLISION_MASK_WEAPON_TYPE_ENERGY = 16;
var COLLISION_MASK_WEAPON_TYPE_PROJECTILE = 32;
var COLLISION_TYPE_SPHERE = 1;
var COLLISION_TYPE_BOX = 2;
